package com.land.pojo;

import com.land.common.BasePojo;

public class Resource extends BasePojo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.id
     *
     * @mbggenerated Thu Nov 09 15:10:41 CST 2017
     */
    private Byte id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.name
     *
     * @mbggenerated Thu Nov 09 15:10:41 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.permission
     *
     * @mbggenerated Thu Nov 09 15:10:41 CST 2017
     */
    private String permission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.url
     *
     * @mbggenerated Thu Nov 09 15:10:41 CST 2017
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.id
     *
     * @return the value of t_resource.id
     *
     * @mbggenerated Thu Nov 09 15:10:41 CST 2017
     */
    public Byte getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.id
     *
     * @param id the value for t_resource.id
     *
     * @mbggenerated Thu Nov 09 15:10:41 CST 2017
     */
    public void setId(Byte id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.name
     *
     * @return the value of t_resource.name
     *
     * @mbggenerated Thu Nov 09 15:10:41 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.name
     *
     * @param name the value for t_resource.name
     *
     * @mbggenerated Thu Nov 09 15:10:41 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.permission
     *
     * @return the value of t_resource.permission
     *
     * @mbggenerated Thu Nov 09 15:10:41 CST 2017
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.permission
     *
     * @param permission the value for t_resource.permission
     *
     * @mbggenerated Thu Nov 09 15:10:41 CST 2017
     */
    public void setPermission(String permission) {
        this.permission = permission == null ? null : permission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.url
     *
     * @return the value of t_resource.url
     *
     * @mbggenerated Thu Nov 09 15:10:41 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.url
     *
     * @param url the value for t_resource.url
     *
     * @mbggenerated Thu Nov 09 15:10:41 CST 2017
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }
}