package com.land.pojo;

import com.land.common.BasePojo;

public class Role extends BasePojo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.id
     *
     * @mbggenerated Thu Nov 09 15:10:41 CST 2017
     */
    private Byte id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.name
     *
     * @mbggenerated Thu Nov 09 15:10:41 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.sn
     *
     * @mbggenerated Thu Nov 09 15:10:41 CST 2017
     */
    private String sn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.id
     *
     * @return the value of t_role.id
     *
     * @mbggenerated Thu Nov 09 15:10:41 CST 2017
     */
    public Byte getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.id
     *
     * @param id the value for t_role.id
     *
     * @mbggenerated Thu Nov 09 15:10:41 CST 2017
     */
    public void setId(Byte id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.name
     *
     * @return the value of t_role.name
     *
     * @mbggenerated Thu Nov 09 15:10:41 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.name
     *
     * @param name the value for t_role.name
     *
     * @mbggenerated Thu Nov 09 15:10:41 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.sn
     *
     * @return the value of t_role.sn
     *
     * @mbggenerated Thu Nov 09 15:10:41 CST 2017
     */
    public String getSn() {
        return sn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.sn
     *
     * @param sn the value for t_role.sn
     *
     * @mbggenerated Thu Nov 09 15:10:41 CST 2017
     */
    public void setSn(String sn) {
        this.sn = sn == null ? null : sn.trim();
    }
}